#!/usr/bin/env python3
"""Generate the repo-root .clangd for C++/CUDA IntelliSense (CMake-free).

This replaces the old CMake `configure_file(.clangd.in -> .clangd)` step. It injects the CUTLASS,
csrc, and (best-effort) PyTorch include paths so clangd resolves headers in the kernel `.cu/.cuh`
and binding `.cu` files, and strips nvcc-only flags clangd can't parse. `.clangd` is gitignored
(absolute, machine-specific paths); re-run this after moving the tree or changing the Python env:

    python scripts/gen_clangd.py
"""

from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
CUTLASS = ROOT / "3rdparty" / "cutlass"
CSRC = ROOT / "csrc"

include_dirs = [
    CUTLASS / "include",
    CUTLASS / "tools" / "util" / "include",
    CUTLASS / "examples" / "common",
    CSRC / "cute",
    CSRC / "cute" / "gemm" / "hopper",
    CSRC / "cute" / "gemm" / "hopper" / "gemm_sm90",
    CSRC / "cute" / "gemm" / "hopper" / "pipeline_gemm",
    CSRC / "cute" / "gemm" / "hopper" / "pipeline_gemm" / "gemm_multistage",
    CSRC / "cute" / "gemm" / "hopper" / "pipeline_gemm" / "gemm_warp_specialization",
    CSRC / "cute" / "gemm" / "hopper" / "pipeline_gemm" / "gemm_warp_specialization" / "kernel",
    CSRC / "cute" / "gemm" / "hopper" / "evt_gemm",
    CSRC / "cute" / "fmha" / "hopper",
    CSRC / "cute" / "fmha" / "hopper" / "lib" / "gemm",
]

# Best-effort PyTorch + Python headers so the binding *.cu files resolve <torch/extension.h>.
try:
    import sysconfig

    import torch.utils.cpp_extension as cpp_ext

    include_dirs += [Path(p) for p in cpp_ext.include_paths()]
    py_inc = sysconfig.get_path("include")
    if py_inc:
        include_dirs.append(Path(py_inc))
except Exception:
    pass  # torch not importable -> kernels still index; binding torch headers won't resolve

adds = "\n".join(f"    - -I{d}" for d in include_dirs)

clangd = f"""# Generated by scripts/gen_clangd.py (CMake-free). Edit that script, not this file, and
# re-run it after moving the tree or changing the Python/torch environment.
#
# nvcc-only flags are stripped (Remove:) because clangd's clang frontend can't parse them.
CompileFlags:
  Add:
{adds}
    - --no-cuda-version-check
    - -DCOMPILE_3X_HOPPER
  Remove:
    - -forward-unknown-to-host-compiler
    - --options-file*
    - --generate-code*
    - -gencode*
    - --expt-*
    - -arch=*
    - --use_fast_math
    - --compiler-options*
    - -Xptxas*
    - -Xcompiler*
    - -ccbin*

Diagnostics:
  UnusedIncludes: None
  Suppress:
    - unknown_cuda_version
"""

out = ROOT / ".clangd"
out.write_text(clangd)
print(f"wrote {out} ({len(include_dirs)} include dirs)")
