#!/usr/bin/env python3
"""Generate the repo-root .clangd for C++/CUDA IntelliSense (CMake-free).

This replaces the old CMake `configure_file(.clangd.in -> .clangd)` step. It injects the CUTLASS,
csrc, and (best-effort) PyTorch include paths so clangd resolves headers in the kernel `.cu/.cuh`
and binding `.cu` files, and strips nvcc-only flags clangd can't parse. `.clangd` is gitignored
(absolute, machine-specific paths); re-run this after moving the tree or changing the Python env:

    python scripts/gen_clangd.py
"""

import os
import shutil
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
CUTLASS = ROOT / "3rdparty" / "cutlass"
CSRC = ROOT / "csrc"


def find_cuda_path():
    """Locate the CUDA toolkit so clangd can parse .cu/.cuh as CUDA (-std/builtins/headers)."""
    for env in ("CUDA_HOME", "CUDA_PATH"):
        p = os.environ.get(env)
        if p and (Path(p) / "include" / "cuda_runtime.h").exists():
            return Path(p)
    nvcc = shutil.which("nvcc")
    if nvcc:
        # <cuda>/bin/nvcc -> <cuda>
        return Path(nvcc).resolve().parents[1]
    default = Path("/usr/local/cuda")
    return default if (default / "include" / "cuda_runtime.h").exists() else None

include_dirs = [
    CUTLASS / "include",
    CUTLASS / "tools" / "util" / "include",
    CUTLASS / "examples" / "common",
    CSRC / "cute",
    CSRC / "cute" / "gemm" / "hopper",
    CSRC / "cute" / "gemm" / "hopper" / "gemm_sm90",
    CSRC / "cute" / "gemm" / "hopper" / "pipeline_gemm",
    CSRC / "cute" / "gemm" / "hopper" / "pipeline_gemm" / "gemm_multistage",
    CSRC / "cute" / "gemm" / "hopper" / "pipeline_gemm" / "gemm_warp_specialization",
    CSRC / "cute" / "gemm" / "hopper" / "pipeline_gemm" / "gemm_warp_specialization" / "kernel",
    CSRC / "cute" / "gemm" / "hopper" / "evt_gemm",
    CSRC / "cute" / "fmha" / "hopper",
    CSRC / "cute" / "fmha" / "hopper" / "lib" / "gemm",
]

# Best-effort PyTorch + Python headers so the binding *.cu files resolve <torch/extension.h>.
try:
    import sysconfig

    import torch.utils.cpp_extension as cpp_ext

    include_dirs += [Path(p) for p in cpp_ext.include_paths()]
    py_inc = sysconfig.get_path("include")
    if py_inc:
        include_dirs.append(Path(py_inc))
except Exception:
    pass  # torch not importable -> kernels still index; binding torch headers won't resolve

adds = "\n".join(f"    - -I{d}" for d in include_dirs)

# C++ standard must match the build (-std=c++17); without it clangd defaults to an older standard
# and floods CUTLASS's C++17 headers with parse errors. --cuda-path points clangd at the toolkit so
# it parses CUDA in CUDA mode (resolves <cuda_runtime.h>, __global__/__device__, etc.).
#
# -x cuda forces CUDA language mode for every file clangd opens in this tree. clang maps the .cu
# extension to CUDA automatically, but does NOT recognize .cuh (nor the loose .h/.hpp kernel headers
# like online_softmax.h and lib/gemm/*.hpp), so without this clangd parses those as plain C++ and
# fails to resolve CUDA builtins and the CUTLASS/CuTe headers — i.e. no IntelliSense in .cuh files.
# VS Code's files.associations (*.cuh -> cuda-cpp) does NOT fix this: clangd ignores it and picks the
# language itself. The flag must be two separate list items ("-x", "cuda") — clangd treats each Add
# entry as one argument and does not split on spaces, so "-x cuda" on one line would be mispassed.
cuda_path = find_cuda_path()
extra = ["    - -std=c++17", "    - -x", "    - cuda"]
if cuda_path:
    extra.append(f"    - --cuda-path={cuda_path}")
extra = "\n".join(extra)

clangd = f"""# Generated by scripts/gen_clangd.py (CMake-free). Edit that script, not this file, and
# re-run it after moving the tree or changing the Python/torch environment.
#
# nvcc-only flags are stripped (Remove:) because clangd's clang frontend can't parse them.
CompileFlags:
  Add:
{adds}
{extra}
    - --no-cuda-version-check
    - -DCOMPILE_3X_HOPPER
  Remove:
    - -forward-unknown-to-host-compiler
    - --options-file*
    - --generate-code*
    - -gencode*
    - --expt-*
    - -arch=*
    - --use_fast_math
    - --compiler-options*
    - -Xptxas*
    - -Xcompiler*
    - -ccbin*

Diagnostics:
  UnusedIncludes: None
  Suppress:
    - unknown_cuda_version
"""

out = ROOT / ".clangd"
out.write_text(clangd)
cuda_note = f"cuda-path={cuda_path}" if cuda_path else "cuda-path NOT found (CUDA headers may not resolve)"
print(f"wrote {out} ({len(include_dirs)} include dirs, -std=c++17, {cuda_note})")
